import type { NextPage } from 'next'
import styles from '../styles/Home.module.css'
import Layout from '../component/Layout'
import Image from 'next/image';

const Home: NextPage = () => {
  return (
      <Layout pageTitle='Home Page'>  
        <Image src="/profile.jpeg" width={180} height={200} alt="profile" />
        <h1 className={styles['title-homepage']}>Welcome Ading</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in ligula ut tortor finibus faucibus. Aliquam est nunc, efficitur vel ligula sed, euismod venenatis diam. Etiam mi ligula, consequat et consequat eget, elementum pulvinar elit. In et molestie dolor, blandit hendrerit velit. Aenean pellentesque felis eu nunc placerat volutpat. Maecenas ac placerat purus. Vivamus magna eros, egestas mollis lacus ac, egestas dignissim lectus. Praesent nisi eros, hendrerit ac porta et, tempor nec velit. Suspendisse ut sapien vel dolor imperdiet congue. Nulla quis scelerisque nulla. Nulla facilisi.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in ligula ut tortor finibus faucibus. Aliquam est nunc, efficitur vel ligula sed, euismod venenatis diam. Etiam mi ligula, consequat et consequat eget, elementum pulvinar elit. In et molestie dolor, blandit hendrerit velit. Aenean pellentesque felis eu nunc placerat volutpat. Maecenas ac placerat purus. Vivamus magna eros, egestas mollis lacus ac, egestas dignissim lectus. Praesent nisi eros, hendrerit ac porta et, tempor nec velit. Suspendisse ut sapien vel dolor imperdiet congue. Nulla quis scelerisque nulla. Nulla facilisi.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in ligula ut tortor finibus faucibus. Aliquam est nunc, efficitur vel ligula sed, euismod venenatis diam. Etiam mi ligula, consequat et consequat eget, elementum pulvinar elit. In et molestie dolor, blandit hendrerit velit. Aenean pellentesque felis eu nunc placerat volutpat. Maecenas ac placerat purus. Vivamus magna eros, egestas mollis lacus ac, egestas dignissim lectus. Praesent nisi eros, hendrerit ac porta et, tempor nec velit. Suspendisse ut sapien vel dolor imperdiet congue. Nulla quis scelerisque nulla. Nulla facilisi.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in ligula ut tortor finibus faucibus. Aliquam est nunc, efficitur vel ligula sed, euismod venenatis diam. Etiam mi ligula, consequat et consequat eget, elementum pulvinar elit. In et molestie dolor, blandit hendrerit velit. Aenean pellentesque felis eu nunc placerat volutpat. Maecenas ac placerat purus. Vivamus magna eros, egestas mollis lacus ac, egestas dignissim lectus. Praesent nisi eros, hendrerit ac porta et, tempor nec velit. Suspendisse ut sapien vel dolor imperdiet congue. Nulla quis scelerisque nulla. Nulla facilisi.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in ligula ut tortor finibus faucibus. Aliquam est nunc, efficitur vel ligula sed, euismod venenatis diam. Etiam mi ligula, consequat et consequat eget, elementum pulvinar elit. In et molestie dolor, blandit hendrerit velit. Aenean pellentesque felis eu nunc placerat volutpat. Maecenas ac placerat purus. Vivamus magna eros, egestas mollis lacus ac, egestas dignissim lectus. Praesent nisi eros, hendrerit ac porta et, tempor nec velit. Suspendisse ut sapien vel dolor imperdiet congue. Nulla quis scelerisque nulla. Nulla facilisi.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in ligula ut tortor finibus faucibus. Aliquam est nunc, efficitur vel ligula sed, euismod venenatis diam. Etiam mi ligula, consequat et consequat eget, elementum pulvinar elit. In et molestie dolor, blandit hendrerit velit. Aenean pellentesque felis eu nunc placerat volutpat. Maecenas ac placerat purus. Vivamus magna eros, egestas mollis lacus ac, egestas dignissim lectus. Praesent nisi eros, hendrerit ac porta et, tempor nec velit. Suspendisse ut sapien vel dolor imperdiet congue. Nulla quis scelerisque nulla. Nulla facilisi.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in ligula ut tortor finibus faucibus. Aliquam est nunc, efficitur vel ligula sed, euismod venenatis diam. Etiam mi ligula, consequat et consequat eget, elementum pulvinar elit. In et molestie dolor, blandit hendrerit velit. Aenean pellentesque felis eu nunc placerat volutpat. Maecenas ac placerat purus. Vivamus magna eros, egestas mollis lacus ac, egestas dignissim lectus. Praesent nisi eros, hendrerit ac porta et, tempor nec velit. Suspendisse ut sapien vel dolor imperdiet congue. Nulla quis scelerisque nulla. Nulla facilisi.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in ligula ut tortor finibus faucibus. Aliquam est nunc, efficitur vel ligula sed, euismod venenatis diam. Etiam mi ligula, consequat et consequat eget, elementum pulvinar elit. In et molestie dolor, blandit hendrerit velit. Aenean pellentesque felis eu nunc placerat volutpat. Maecenas ac placerat purus. Vivamus magna eros, egestas mollis lacus ac, egestas dignissim lectus. Praesent nisi eros, hendrerit ac porta et, tempor nec velit. Suspendisse ut sapien vel dolor imperdiet congue. Nulla quis scelerisque nulla. Nulla facilisi.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in ligula ut tortor finibus faucibus. Aliquam est nunc, efficitur vel ligula sed, euismod venenatis diam. Etiam mi ligula, consequat et consequat eget, elementum pulvinar elit. In et molestie dolor, blandit hendrerit velit. Aenean pellentesque felis eu nunc placerat volutpat. Maecenas ac placerat purus. Vivamus magna eros, egestas mollis lacus ac, egestas dignissim lectus. Praesent nisi eros, hendrerit ac porta et, tempor nec velit. Suspendisse ut sapien vel dolor imperdiet congue. Nulla quis scelerisque nulla. Nulla facilisi.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in ligula ut tortor finibus faucibus. Aliquam est nunc, efficitur vel ligula sed, euismod venenatis diam. Etiam mi ligula, consequat et consequat eget, elementum pulvinar elit. In et molestie dolor, blandit hendrerit velit. Aenean pellentesque felis eu nunc placerat volutpat. Maecenas ac placerat purus. Vivamus magna eros, egestas mollis lacus ac, egestas dignissim lectus. Praesent nisi eros, hendrerit ac porta et, tempor nec velit. Suspendisse ut sapien vel dolor imperdiet congue. Nulla quis scelerisque nulla. Nulla facilisi.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in ligula ut tortor finibus faucibus. Aliquam est nunc, efficitur vel ligula sed, euismod venenatis diam. Etiam mi ligula, consequat et consequat eget, elementum pulvinar elit. In et molestie dolor, blandit hendrerit velit. Aenean pellentesque felis eu nunc placerat volutpat. Maecenas ac placerat purus. Vivamus magna eros, egestas mollis lacus ac, egestas dignissim lectus. Praesent nisi eros, hendrerit ac porta et, tempor nec velit. Suspendisse ut sapien vel dolor imperdiet congue. Nulla quis scelerisque nulla. Nulla facilisi.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in ligula ut tortor finibus faucibus. Aliquam est nunc, efficitur vel ligula sed, euismod venenatis diam. Etiam mi ligula, consequat et consequat eget, elementum pulvinar elit. In et molestie dolor, blandit hendrerit velit. Aenean pellentesque felis eu nunc placerat volutpat. Maecenas ac placerat purus. Vivamus magna eros, egestas mollis lacus ac, egestas dignissim lectus. Praesent nisi eros, hendrerit ac porta et, tempor nec velit. Suspendisse ut sapien vel dolor imperdiet congue. Nulla quis scelerisque nulla. Nulla facilisi.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in ligula ut tortor finibus faucibus. Aliquam est nunc, efficitur vel ligula sed, euismod venenatis diam. Etiam mi ligula, consequat et consequat eget, elementum pulvinar elit. In et molestie dolor, blandit hendrerit velit. Aenean pellentesque felis eu nunc placerat volutpat. Maecenas ac placerat purus. Vivamus magna eros, egestas mollis lacus ac, egestas dignissim lectus. Praesent nisi eros, hendrerit ac porta et, tempor nec velit. Suspendisse ut sapien vel dolor imperdiet congue. Nulla quis scelerisque nulla. Nulla facilisi.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in ligula ut tortor finibus faucibus. Aliquam est nunc, efficitur vel ligula sed, euismod venenatis diam. Etiam mi ligula, consequat et consequat eget, elementum pulvinar elit. In et molestie dolor, blandit hendrerit velit. Aenean pellentesque felis eu nunc placerat volutpat. Maecenas ac placerat purus. Vivamus magna eros, egestas mollis lacus ac, egestas dignissim lectus. Praesent nisi eros, hendrerit ac porta et, tempor nec velit. Suspendisse ut sapien vel dolor imperdiet congue. Nulla quis scelerisque nulla. Nulla facilisi.</p>

        <Image src="/post1.jpeg" width={180} height={200} alt="profile" />
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in ligula ut tortor finibus faucibus. Aliquam est nunc, efficitur vel ligula sed, euismod venenatis diam. Etiam mi ligula, consequat et consequat eget, elementum pulvinar elit. In et molestie dolor, blandit hendrerit velit. Aenean pellentesque felis eu nunc placerat volutpat. Maecenas ac placerat purus. Vivamus magna eros, egestas mollis lacus ac, egestas dignissim lectus. Praesent nisi eros, hendrerit ac porta et, tempor nec velit. Suspendisse ut sapien vel dolor imperdiet congue. Nulla quis scelerisque nulla. Nulla facilisi.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in ligula ut tortor finibus faucibus. Aliquam est nunc, efficitur vel ligula sed, euismod venenatis diam. Etiam mi ligula, consequat et consequat eget, elementum pulvinar elit. In et molestie dolor, blandit hendrerit velit. Aenean pellentesque felis eu nunc placerat volutpat. Maecenas ac placerat purus. Vivamus magna eros, egestas mollis lacus ac, egestas dignissim lectus. Praesent nisi eros, hendrerit ac porta et, tempor nec velit. Suspendisse ut sapien vel dolor imperdiet congue. Nulla quis scelerisque nulla. Nulla facilisi.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in ligula ut tortor finibus faucibus. Aliquam est nunc, efficitur vel ligula sed, euismod venenatis diam. Etiam mi ligula, consequat et consequat eget, elementum pulvinar elit. In et molestie dolor, blandit hendrerit velit. Aenean pellentesque felis eu nunc placerat volutpat. Maecenas ac placerat purus. Vivamus magna eros, egestas mollis lacus ac, egestas dignissim lectus. Praesent nisi eros, hendrerit ac porta et, tempor nec velit. Suspendisse ut sapien vel dolor imperdiet congue. Nulla quis scelerisque nulla. Nulla facilisi.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in ligula ut tortor finibus faucibus. Aliquam est nunc, efficitur vel ligula sed, euismod venenatis diam. Etiam mi ligula, consequat et consequat eget, elementum pulvinar elit. In et molestie dolor, blandit hendrerit velit. Aenean pellentesque felis eu nunc placerat volutpat. Maecenas ac placerat purus. Vivamus magna eros, egestas mollis lacus ac, egestas dignissim lectus. Praesent nisi eros, hendrerit ac porta et, tempor nec velit. Suspendisse ut sapien vel dolor imperdiet congue. Nulla quis scelerisque nulla. Nulla facilisi.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in ligula ut tortor finibus faucibus. Aliquam est nunc, efficitur vel ligula sed, euismod venenatis diam. Etiam mi ligula, consequat et consequat eget, elementum pulvinar elit. In et molestie dolor, blandit hendrerit velit. Aenean pellentesque felis eu nunc placerat volutpat. Maecenas ac placerat purus. Vivamus magna eros, egestas mollis lacus ac, egestas dignissim lectus. Praesent nisi eros, hendrerit ac porta et, tempor nec velit. Suspendisse ut sapien vel dolor imperdiet congue. Nulla quis scelerisque nulla. Nulla facilisi.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in ligula ut tortor finibus faucibus. Aliquam est nunc, efficitur vel ligula sed, euismod venenatis diam. Etiam mi ligula, consequat et consequat eget, elementum pulvinar elit. In et molestie dolor, blandit hendrerit velit. Aenean pellentesque felis eu nunc placerat volutpat. Maecenas ac placerat purus. Vivamus magna eros, egestas mollis lacus ac, egestas dignissim lectus. Praesent nisi eros, hendrerit ac porta et, tempor nec velit. Suspendisse ut sapien vel dolor imperdiet congue. Nulla quis scelerisque nulla. Nulla facilisi.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in ligula ut tortor finibus faucibus. Aliquam est nunc, efficitur vel ligula sed, euismod venenatis diam. Etiam mi ligula, consequat et consequat eget, elementum pulvinar elit. In et molestie dolor, blandit hendrerit velit. Aenean pellentesque felis eu nunc placerat volutpat. Maecenas ac placerat purus. Vivamus magna eros, egestas mollis lacus ac, egestas dignissim lectus. Praesent nisi eros, hendrerit ac porta et, tempor nec velit. Suspendisse ut sapien vel dolor imperdiet congue. Nulla quis scelerisque nulla. Nulla facilisi.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in ligula ut tortor finibus faucibus. Aliquam est nunc, efficitur vel ligula sed, euismod venenatis diam. Etiam mi ligula, consequat et consequat eget, elementum pulvinar elit. In et molestie dolor, blandit hendrerit velit. Aenean pellentesque felis eu nunc placerat volutpat. Maecenas ac placerat purus. Vivamus magna eros, egestas mollis lacus ac, egestas dignissim lectus. Praesent nisi eros, hendrerit ac porta et, tempor nec velit. Suspendisse ut sapien vel dolor imperdiet congue. Nulla quis scelerisque nulla. Nulla facilisi.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in ligula ut tortor finibus faucibus. Aliquam est nunc, efficitur vel ligula sed, euismod venenatis diam. Etiam mi ligula, consequat et consequat eget, elementum pulvinar elit. In et molestie dolor, blandit hendrerit velit. Aenean pellentesque felis eu nunc placerat volutpat. Maecenas ac placerat purus. Vivamus magna eros, egestas mollis lacus ac, egestas dignissim lectus. Praesent nisi eros, hendrerit ac porta et, tempor nec velit. Suspendisse ut sapien vel dolor imperdiet congue. Nulla quis scelerisque nulla. Nulla facilisi.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in ligula ut tortor finibus faucibus. Aliquam est nunc, efficitur vel ligula sed, euismod venenatis diam. Etiam mi ligula, consequat et consequat eget, elementum pulvinar elit. In et molestie dolor, blandit hendrerit velit. Aenean pellentesque felis eu nunc placerat volutpat. Maecenas ac placerat purus. Vivamus magna eros, egestas mollis lacus ac, egestas dignissim lectus. Praesent nisi eros, hendrerit ac porta et, tempor nec velit. Suspendisse ut sapien vel dolor imperdiet congue. Nulla quis scelerisque nulla. Nulla facilisi.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in ligula ut tortor finibus faucibus. Aliquam est nunc, efficitur vel ligula sed, euismod venenatis diam. Etiam mi ligula, consequat et consequat eget, elementum pulvinar elit. In et molestie dolor, blandit hendrerit velit. Aenean pellentesque felis eu nunc placerat volutpat. Maecenas ac placerat purus. Vivamus magna eros, egestas mollis lacus ac, egestas dignissim lectus. Praesent nisi eros, hendrerit ac porta et, tempor nec velit. Suspendisse ut sapien vel dolor imperdiet congue. Nulla quis scelerisque nulla. Nulla facilisi.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in ligula ut tortor finibus faucibus. Aliquam est nunc, efficitur vel ligula sed, euismod venenatis diam. Etiam mi ligula, consequat et consequat eget, elementum pulvinar elit. In et molestie dolor, blandit hendrerit velit. Aenean pellentesque felis eu nunc placerat volutpat. Maecenas ac placerat purus. Vivamus magna eros, egestas mollis lacus ac, egestas dignissim lectus. Praesent nisi eros, hendrerit ac porta et, tempor nec velit. Suspendisse ut sapien vel dolor imperdiet congue. Nulla quis scelerisque nulla. Nulla facilisi.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in ligula ut tortor finibus faucibus. Aliquam est nunc, efficitur vel ligula sed, euismod venenatis diam. Etiam mi ligula, consequat et consequat eget, elementum pulvinar elit. In et molestie dolor, blandit hendrerit velit. Aenean pellentesque felis eu nunc placerat volutpat. Maecenas ac placerat purus. Vivamus magna eros, egestas mollis lacus ac, egestas dignissim lectus. Praesent nisi eros, hendrerit ac porta et, tempor nec velit. Suspendisse ut sapien vel dolor imperdiet congue. Nulla quis scelerisque nulla. Nulla facilisi.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in ligula ut tortor finibus faucibus. Aliquam est nunc, efficitur vel ligula sed, euismod venenatis diam. Etiam mi ligula, consequat et consequat eget, elementum pulvinar elit. In et molestie dolor, blandit hendrerit velit. Aenean pellentesque felis eu nunc placerat volutpat. Maecenas ac placerat purus. Vivamus magna eros, egestas mollis lacus ac, egestas dignissim lectus. Praesent nisi eros, hendrerit ac porta et, tempor nec velit. Suspendisse ut sapien vel dolor imperdiet congue. Nulla quis scelerisque nulla. Nulla facilisi.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in ligula ut tortor finibus faucibus. Aliquam est nunc, efficitur vel ligula sed, euismod venenatis diam. Etiam mi ligula, consequat et consequat eget, elementum pulvinar elit. In et molestie dolor, blandit hendrerit velit. Aenean pellentesque felis eu nunc placerat volutpat. Maecenas ac placerat purus. Vivamus magna eros, egestas mollis lacus ac, egestas dignissim lectus. Praesent nisi eros, hendrerit ac porta et, tempor nec velit. Suspendisse ut sapien vel dolor imperdiet congue. Nulla quis scelerisque nulla. Nulla facilisi.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in ligula ut tortor finibus faucibus. Aliquam est nunc, efficitur vel ligula sed, euismod venenatis diam. Etiam mi ligula, consequat et consequat eget, elementum pulvinar elit. In et molestie dolor, blandit hendrerit velit. Aenean pellentesque felis eu nunc placerat volutpat. Maecenas ac placerat purus. Vivamus magna eros, egestas mollis lacus ac, egestas dignissim lectus. Praesent nisi eros, hendrerit ac porta et, tempor nec velit. Suspendisse ut sapien vel dolor imperdiet congue. Nulla quis scelerisque nulla. Nulla facilisi.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in ligula ut tortor finibus faucibus. Aliquam est nunc, efficitur vel ligula sed, euismod venenatis diam. Etiam mi ligula, consequat et consequat eget, elementum pulvinar elit. In et molestie dolor, blandit hendrerit velit. Aenean pellentesque felis eu nunc placerat volutpat. Maecenas ac placerat purus. Vivamus magna eros, egestas mollis lacus ac, egestas dignissim lectus. Praesent nisi eros, hendrerit ac porta et, tempor nec velit. Suspendisse ut sapien vel dolor imperdiet congue. Nulla quis scelerisque nulla. Nulla facilisi.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in ligula ut tortor finibus faucibus. Aliquam est nunc, efficitur vel ligula sed, euismod venenatis diam. Etiam mi ligula, consequat et consequat eget, elementum pulvinar elit. In et molestie dolor, blandit hendrerit velit. Aenean pellentesque felis eu nunc placerat volutpat. Maecenas ac placerat purus. Vivamus magna eros, egestas mollis lacus ac, egestas dignissim lectus. Praesent nisi eros, hendrerit ac porta et, tempor nec velit. Suspendisse ut sapien vel dolor imperdiet congue. Nulla quis scelerisque nulla. Nulla facilisi.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in ligula ut tortor finibus faucibus. Aliquam est nunc, efficitur vel ligula sed, euismod venenatis diam. Etiam mi ligula, consequat et consequat eget, elementum pulvinar elit. In et molestie dolor, blandit hendrerit velit. Aenean pellentesque felis eu nunc placerat volutpat. Maecenas ac placerat purus. Vivamus magna eros, egestas mollis lacus ac, egestas dignissim lectus. Praesent nisi eros, hendrerit ac porta et, tempor nec velit. Suspendisse ut sapien vel dolor imperdiet congue. Nulla quis scelerisque nulla. Nulla facilisi.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in ligula ut tortor finibus faucibus. Aliquam est nunc, efficitur vel ligula sed, euismod venenatis diam. Etiam mi ligula, consequat et consequat eget, elementum pulvinar elit. In et molestie dolor, blandit hendrerit velit. Aenean pellentesque felis eu nunc placerat volutpat. Maecenas ac placerat purus. Vivamus magna eros, egestas mollis lacus ac, egestas dignissim lectus. Praesent nisi eros, hendrerit ac porta et, tempor nec velit. Suspendisse ut sapien vel dolor imperdiet congue. Nulla quis scelerisque nulla. Nulla facilisi.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in ligula ut tortor finibus faucibus. Aliquam est nunc, efficitur vel ligula sed, euismod venenatis diam. Etiam mi ligula, consequat et consequat eget, elementum pulvinar elit. In et molestie dolor, blandit hendrerit velit. Aenean pellentesque felis eu nunc placerat volutpat. Maecenas ac placerat purus. Vivamus magna eros, egestas mollis lacus ac, egestas dignissim lectus. Praesent nisi eros, hendrerit ac porta et, tempor nec velit. Suspendisse ut sapien vel dolor imperdiet congue. Nulla quis scelerisque nulla. Nulla facilisi.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in ligula ut tortor finibus faucibus. Aliquam est nunc, efficitur vel ligula sed, euismod venenatis diam. Etiam mi ligula, consequat et consequat eget, elementum pulvinar elit. In et molestie dolor, blandit hendrerit velit. Aenean pellentesque felis eu nunc placerat volutpat. Maecenas ac placerat purus. Vivamus magna eros, egestas mollis lacus ac, egestas dignissim lectus. Praesent nisi eros, hendrerit ac porta et, tempor nec velit. Suspendisse ut sapien vel dolor imperdiet congue. Nulla quis scelerisque nulla. Nulla facilisi.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in ligula ut tortor finibus faucibus. Aliquam est nunc, efficitur vel ligula sed, euismod venenatis diam. Etiam mi ligula, consequat et consequat eget, elementum pulvinar elit. In et molestie dolor, blandit hendrerit velit. Aenean pellentesque felis eu nunc placerat volutpat. Maecenas ac placerat purus. Vivamus magna eros, egestas mollis lacus ac, egestas dignissim lectus. Praesent nisi eros, hendrerit ac porta et, tempor nec velit. Suspendisse ut sapien vel dolor imperdiet congue. Nulla quis scelerisque nulla. Nulla facilisi.</p>
        
        <Image src="/post2.jpeg" width={180} height={200} alt="profile" />
      </Layout>
  )
}

export default Home
